Update 'Building your own LoRa network' article to new LoRaWAN stack
ARMmbed/lora-docs pull request #13
Opened 2018-02-13 06:21 UTC by janjongboom

Update for 2018.

1. Change to use the Mbed OS 5.8 LoRaWAN stack.
1. Switch to The Things Network as it's free, contrary to IoT-X and LORIOT - so more useful for first-timers.
1. Add a bunch of clarification around radio, LoRaWAN in general, etc.
1. Change to use OTA instead of ABP - it's 2018, we should not use ABP anymore.
1. Add some notes on LoRaWAN 1.1.
1. Add a nice demo web app which looks better than the old one.

@hasnainvirk @johanstokking Any initial feedback? Gateway setup instructions are still missing for Kerlink + RPi. Docs on TTN are very sparse. Rest should be good.

2018-02-14 16:29 UTC, johanstokking commented
Looks good but I don't see a README

2018-02-15 04:21 UTC, janjongboom commented
@johanstokking No, because it'll be published on our docs site, not on GitHub.

2018-02-15 05:29 UTC, janjongboom commented
@iriark01 @AnotherButler This is ready for review.

2018-02-15 09:51 UTC, hasnainvirk approved these changes
Looks good.

2018-02-27 13:13 UTC, janjongboom commented on docs/intro-to-lora.md
> +Because a network server only processes your data and doesn't store it, you need a somewhere to store your messages as well. The Things Network allows you to hook into their service through an MQTT c
This sentence does not make sense anymore now.

2018-02-27 13:17 UTC, janjongboom commented
@fheathco Small nit, other than that it looks good.

2018-03-01 00:05 UTC, AnotherButler requested changes
I've left some comments and queries for you to address. Also, do you know where this is going in the docs? Is it on the Mbed OS site or somewhere else?

2018-03-01 00:05 UTC, AnotherButler commented on docs/intro-to-lora.md
> +    <span class="images">![Gateway details](assets/ttn3.png)<span>Gateway details: Make sure to set the location correctly, so coverage maps can be updated.</span></span>
Query: Who or what updates the coverage maps?

2018-03-01 00:05 UTC, AnotherButler commented on docs/intro-to-lora.md
> +The device EUI and application EUI are globally unique identifiers. You can buy a block of EUIs from the [IEEE](http://standards.ieee.org/develop/regauth/tut/eui.pdf). If you're using a module, it ma
Query: "If you're using a module, it may have an EUI printed on the module." Should "module" be in there twice?

2018-03-01 00:05 UTC, AnotherButler commented on docs/intro-to-lora.md
> +1. Go to [mbed-os-example-lorawan]().
Note: This link is empty.

2018-03-01 00:05 UTC, AnotherButler commented on docs/intro-to-lora.md
> +    <span class="images"><span>We've got data! **TODO: add image**</span></span>
Note: There's a TODO here.

2018-03-01 00:05 UTC, AnotherButler commented on docs/intro-to-lora.md
> +- [Mbed OS LoRaWAN stack documentation]().
Note: This link is missing.

2018-03-01 00:06 UTC, AnotherButler commented
@janjongboom Also, we now host our images to AWS. Once we know where these docs will live, we need to place the images to the relevant images folder and have them uploaded to AWS.

2018-03-01 09:18 UTC, janjongboom commented on docs/intro-to-lora.md
> +- [Mbed OS LoRaWAN stack documentation]().
Yes, the docs are not online yet.

2018-03-15 17:57 UTC, janjongboom commented
@AnotherButler Sorry, completely missed that you already looked at it. Fixed your comments.

2018-03-19 10:42 UTC, MarceloSalazar commented
@all we're waiting for this to be merged to evaluate Lora during OOB.

2018-03-19 14:48 UTC, janjongboom commented
@MarceloSalazar But we cannot publish this before 5.8 is out. Can you link to https://github.com/ARMmbed/lora-docs/blob/arm-lora-stack/docs/intro-to-lora.md in OOB docs?

@AnotherButler is this good to go now?

2018-03-19 15:14 UTC, MarceloSalazar commented
@janjongboom the doc has to be merged into the right repo/branch to make it available in the internal docs staging environment. Can you please raise that?

2018-03-19 15:16 UTC, AnotherButler commented
@janjongboom Yes, please merge at your convenience. 

Also, we prefer not to link to GH in our docs. Please link to the LoRa page on os.mbed.com instead. In the future, please make all edits to that location once redirects are in place.

@MarceloSalazar I'm on it. I'm making sure it goes to the internal staging site.

2018-03-19 16:24 UTC, AnotherButler approved these changes

2018-03-19 16:50 UTC, merged